<?php

namespace App\Command;

use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Exception;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Throwable;

#[AsCommand(
    name: 'Create:User',
    description: 'create a user in DB',
)]
class CreateUserCommand extends Command
{
    public const PASSWORD_PARTS = [
        'Aalsuppe',
        'Agavendicksaft',
        'Ahornsirup',
        'Ajvar',
        'Ananas',
        'Anis',
        'Anona',
        'Apfel',
        'Apfelkompott',
        'Apfelkraut',
        'Apfelsine',
        'Aprikose',
        'Artischocke',
        'Artischockenherz',
        'Aubergine',
        'Auflauf',
        'Austernpilz',
        'Avocado',
        'Backaroma',
        'Backfett',
        'Backware',
        'Backwerk',
        'Baiser',
        'Balsamessig',
        'Balsamico',
        'Banane',
        'Basilikum',
        'Bauernbrot',
        'Bergkäse',
        'Bienenstich',
        'Bier',
        'Birne',
        'Biskuitteig',
        'Bitterschokolade',
        'Blattsalat',
        'Blattspinat',
        'Blaubeere',
        'Blaukohl',
        'Blaukraut',
        'Blauschimmelkäse',
        'Blätterteig',
        'Blumenkohl',
        'Blutorange',
        'Blutwurst',
        'Blütenhonig',
        'Bockwurst',
        'Bohne',
        'Bohnenkraut',
        'Bohnensuppe',
        'Borschtsch',
        'Boskop',
        'Bouillon',
        'Bouillonwürfel',
        'Bratapfel',
        'Bratwurst',
        'Broccoli',
        'Brokkoli',
        'Brombeere',
        'Brot',
        'Brotaufstrich',
        'Brotsuppe',
        'Brotteig',
        'Brunnenkresse',
        'Brühwürfel',
        'Buchweizen',
        'Bulgur',
        'Butter',
        'Buttercreme',
        'Buttergebäck',
        'Butterkäse',
        'Butterkeks',
        'Butterpilz',
        'Büchsenmilch',
        'Béchamelsauce',
        'Béchamelsoße',
        'Calzone',
        'Camembert',
        'Cannelloni',
        'Cashew',
        'Cashewnuss',
        'Cayennepfeffer',
        'Champignon',
        'Cheddarkäse',
        'Chester',
        'Chesterkäse',
        'Chiasamen',
        'Chicken Nugetts',
        'Chicorée',
        'Chili',
        'Chilisauce',
        'Chilisoße',
        'Chinakohl',
        'Chips',
        'Chorizo',
        'Christstollen',
        'Ciabatta',
        'Citrusfrucht',
        'Clementine',
        'Consommé',
        'Cookie',
        'Corned beef',
        'Cornflakes',
        'Couscous',
        'Cranberry',
        'Croissant',
        'Crème fraîche',
        'Curry',
        'Currypulver',
        'Currysauce',
        'Currysoße',
        'Currywurst',
        'Dampfnudel',
        'Dattel',
        'Dattelbrot',
        'Dattelpflaume',
        'Datteltraube',
        'Dauerwurst',
        'Deichkäse',
        'Delikatesse',
        'Delikatessgurke',
        'Delikatesssenf',
        'Dessert',
        'Diätzucker',
        'Dickmilch',
        'Dill',
        'Dinkel',
        'Dinkelmehl',
        'Distelöl',
        'Dominostein',
        'Dosenfleisch',
        'Dosenmilch',
        'Dosensuppe',
        'Dosenwurst',
        'Döner',
        'Dörrfleisch',
        'Dörrgemüse',
        'Dörrobst',
        'Dörrpflaume',
        'Dressing',
        'Drops',
        'Edamer',
        'Edelpilzkäse',
        'Ei',
        'Eierkuchen',
        'Eigelb',
        'Einbrennsuppe',
        'Eingemachtes',
        'Eingetropftes',
        'Eintopf',
        'Eis',
        'Eisbein',
        'Eisbergsalat',
        'Emmentaler',
        'Ente',
        'Entenbrust',
        'Entenklein',
        'Erbse',
        'Erbsensuppe',
        'Erdbeere',
        'Erdbeergelee',
        'Erdnuss',
        'Erdnussbutter',
        'Erdnussflip',
        'Erdnussmus',
        'Erdnussöl',
        'Esrom',
        'Essig',
        'Essiggurke',
        'Esskastanie',
        'Esswaren',
        'Estragon',
        'Feige',
        'Feinbackwaren',
        'Feingebäck',
        'Feinkost',
        'Felchen',
        'Feldbohne',
        'Feldfrucht',
        'Feldsalat',
        'Fenchel',
        'Feta',
        'Fett',
        'Fettuccine',
        'Filet',
        'Fisch',
        'Fischfilet',
        'Fischkonserve',
        'Fischrogen',
        'Fischstäbchen',
        'Fischsuppe',
        'Fladenbrot',
        'Flammkuchen',
        'Flädlesuppe',
        'Flädlisuppe',
        'Fleckerlsuppe',
        'Fleischbrühe',
        'Fleischkonserve',
        'Fleischsuppe',
        'Fliederbeere',
        'Fliederbeersuppe',
        'Florentiner',
        'Foie gras',
        'Frankfurter',
        'Frikadelle',
        'Frischkäse',
        'Frittatensuppe',
        'Frozen Yogurt',
        'Frucht',
        'Fruchtbonbon',
        'Fruchteis',
        'Fruchtjoghurt',
        'Fruchtjogurt',
        'Früchtebrot',
        'Früchtequark',
        'Frühlingsrolle',
        'Frühlingssuppe',
        'Frühlingszwiebel',
        'Frühstücksbrot',
        'Fufu',
        'Garnele',
        'Gebäck',
        'Gehacktes',
        'Gelee',
        'Gemüsesuppe',
        'Gemüsezwiebel',
        'Gerste',
        'Gerstensuppe',
        'Gerstlsuppe',
        'Getreide',
        'Gewürz',
        'Gewürzgurke',
        'Gnocchi',
        'Gorgonzola',
        'Gouda',
        'Graupe',
        'Graupensuppe',
        'Greyerzer',
        'Grieß',
        'Grießbrei',
        'Grießkloß',
        'Grießklößchen',
        'Grießknödel',
        'Grießmehl',
        'Grießnockerl',
        'Grießpudding',
        'Grießschmarren',
        'Grießsuppe',
        'Grünkohl',
        'Gulasch',
        'Gulaschsuppe',
        'Gurke',
        'Gurkensalat',
        'Gyros',
        'Gyrossalat',
        'Hackepeter',
        'Hackfleisch',
        'Hafer',
        'Haferflocken',
        'Hagebutte',
        'Haifischflossensuppe',
        'Hartkäse',
        'Harzer',
        'Haselnuss',
        'Hefe',
        'Hefezopf',
        'Heidelbeere',
        'Hering',
        'Heringssalat',
        'Hibiskustee',
        'Himbeere',
        'Himbeereis',
        'Himbeertorte',
        'Hirse',
        'Holunderblütensirup',
        'Honig',
        'Honigkuchen',
        'Honigmelone',
        'Hummer',
        'Hummersuppe',
        'Hummus',
        'Hühnerfleisch',
        'Imkerhonig',
        'Ingwer',
        'Instantnudel',
        'Instantpudding',
        'Instantsuppe',
        'Irish Stew',
        'Jagdwurst',
        'Jägerschnitzel',
        'Jägersuppe',
        'Joghurt',
        'Joghurteis',
        'Johannisbeere',
        'Johannisbrot',
        'Julienne',
        'Juliennesuppe',
        'Kakao',
        'Kakaopulver',
        'Kaki',
        'Kaltschale',
        'Kandis',
        'Kandiszucker',
        'Karamell',
        'Karamellbonbon',
        'Karamelleis',
        'Kardamom',
        'Karotte',
        'Kartoffel',
        'Kartoffelchip',
        'Kartoffeln',
        'Kartoffelsuppe',
        'Käse',
        'Käsebrötchen',
        'Käsekuchen',
        'Käsetorte',
        'Keks',
        'Kirsche',
        'Kiwi',
        'Knoblauch',
        'Knoblauchbutter',
        'Knoblauchöl',
        'Knoblauchpulver',
        'Knoblauchsalz',
        'Knoblauchsoße',
        'Knoblauchwurst',
        'Kohl',
        'Kohlroulade',
        'Koriander',
        'Krakauer',
        'Krankensuppe',
        'Krapfen',
        'Kraut',
        'Kräuterbutter',
        'Kräuterkäse',
        'Krebsfleisch',
        'Krebssuppe',
        'Kreplach',
        'Kreuzkümmel',
        'Kuchen',
        'Kurkuma',
        'Kümmel',
        'Kürbis',
        'Kürbiskern',
        'Kürbiskernbrot',
        'Kürbissuppe',
        'Labskaus',
        'Lachs',
        'Lakritz',
        'Lammfleisch',
        'Languste',
        'Lasagne',
        'Lauch',
        'Lauchzwiebel',
        'Lebensmittel',
        'Leberkäse',
        'Leberwurst',
        'Lebkuchen',
        'Lebkuchengewürz',
        'Limburger',
        'Limette',
        'Limettentee',
        'Linguine',
        'Linse',
        'Linsensuppe',
        'Lorbeerblatt',
        'Magermilchpulver',
        'Mais',
        'Maisgrieß',
        'Maiskolben',
        'Maismehl',
        'Majoran',
        'Mandarine',
        'Mandel',
        'Mandelkern',
        'Mango',
        'Mangomousse',
        'Maniok',
        'Maracuja',
        'Margarine',
        'Marmelade',
        'Marmorkuchen',
        'Marzipan',
        'Mascarpone',
        'Matcha',
        'Maultaschen',
        'Meerrettich',
        'Mehl',
        'Melone',
        'Mett',
        'Mettwurst',
        'Milchpulver',
        'Milchreis',
        'Milchsuppe',
        'Miso',
        'Mohn',
        'Mohnbrötchen',
        'Mozzarella',
        'Möhre',
        'Mus',
        'Müsli',
        'Nektarinen',
        'Nockerl',
        'Nockerlsuppe',
        'Noisette',
        'Noisetteschokolade',
        'Nougat',
        'Nudeln',
        'Nudelsuppe',
        'Nuss',
        'Nusskuchen',
        'Nussschinken',
        'Nussschokolade',
        'Nutella',
        'Oberländer',
        'Obst',
        'Obstkuchen',
        'Okroschka',
        'Olive',
        'Olivenöl',
        'Omelett',
        'Orange',
        'Orangeat',
        'Oregano',
        'Pampelmuse',
        'Panadelsuppe',
        'Paprika',
        'Paprikapulver',
        'Paranuss',
        'Parmesankäse',
        'Pasta',
        'Pastete',
        'Pastinake',
        'Pecannuss',
        'Pekannuss',
        'Peperoni',
        'Persillade',
        'Pesto',
        'Petersilie',
        'Pfannkuchen',
        'Pfeffer',
        'Pfefferkuchen',
        'Pferdefleisch',
        'Pfifferling',
        'Pfirsich',
        'Pflaume',
        'Pilz',
        'Pilzsuppe',
        'Piment',
        'Pinienkerne',
        'Pistazie',
        'Pita',
        'Pitabrot',
        'Pizza',
        'Plätzchen',
        'Polenta',
        'Pommes frites',
        'Porridge',
        'Posaunensuppe',
        'Potage',
        'Preiselbeere',
        'Puderzucker',
        'Puffreis',
        'Pumpernickel',
        'Putenfleisch',
        'Quark',
        'Quarkbällchen',
        'Quarktasche',
        'Quiche',
        'Quitte',
        'Radicchio',
        'Radieschen',
        'Rahm',
        'Rahmsuppe',
        'Ramen',
        'Ravioli',
        'Räucherlachs',
        'Reis',
        'Reissuppe',
        'Remoulade',
        'Rettich',
        'Rhabarber',
        'Ricotta',
        'Rinderroulade',
        'Rindfleisch',
        'Rindfleischsuppe',
        'Roggen',
        'Roggenbrot',
        'Rohkost',
        'Rohrzucker',
        'Rollmops',
        'Romadur',
        'Rosenkohl',
        'Rosine',
        'Rosinenkuchen',
        'Rosinenschnecke',
        'Rosmarin',
        'Rote Beete',
        'Rotkohl',
        'Rotkraut',
        'Rotschimmelkäse',
        'Rotweinessig',
        'Rucola',
        'Rumfordsuppe',
        'Rumkugel',
        'Rübe',
        'Rübenkraut',
        'Rübenzucker',
        'Salami',
        'Salatgurke',
        'Salbei',
        'Salz',
        'Salzbrezel',
        'Salzgurke',
        'Salzstange',
        'Sardelle',
        'Sauerkraut',
        'Sauermilch',
        'Sauermilchquark',
        'Sauerrahm',
        'Schafskäse',
        'Schalotte',
        'Schildkrötensuppe',
        'Schinken',
        'Schleimsuppe',
        'Schmorbraten',
        'Schnittlauch',
        'Schokolade',
        'Schwalbennestersuppe',
        'Schwarzbrot',
        'Schwarzkümmel',
        'Schwarzwälder Schinken',
        'Schwarzwurzel',
        'Schweinefleisch',
        'Seitan',
        'Sellerie',
        'Senf',
        'Senfgurke',
        'Sesam',
        'Sesambrötchen',
        'Sesamsauce',
        'Soja',
        'Sojasprossen',
        'Soljanka',
        'Sonnenblumenkern',
        'Spaghetti',
        'Spanferkel',
        'Spargel',
        'Spargelsuppe',
        'Spätzle',
        'Spekulatius',
        'Spinat',
        'Spreewaldgurke',
        'Spritzgebäck',
        'Steinpilz',
        'Sternanis',
        'Stollen',
        'Stracciatella',
        'Stutenmilch',
        'Suppenextrakt',
        'Suppenfleisch',
        'Suppengrün',
        'Suppenhuhn',
        'Suppenknochen',
        'Suppenspargel',
        'Suppenwürfel',
        'Sushi',
        'Süßkartoffel',
        'Süßrahm',
        'Süßrahmbutter',
        'Tagessuppe',
        'Tagliatelle',
        'Tahin',
        'Tamarinde',
        'Tapioka',
        'Teewurst',
        'Tellerfleisch',
        'Tempeh',
        'Terrine',
        'Tiefkühlkost',
        'Tiefkühlpizza',
        'Tilsiter',
        'Tiramisu',
        'Toast',
        'Tofu',
        'Tomate',
        'Tomatenmark',
        'Tomatensoße',
        'Tomatensuppe',
        'Topinambur',
        'Tortellini',
        'Trappistenkäse',
        'Traube',
        'Traubenkernöl',
        'Udon',
        'Urbrot',
        'Vanille',
        'Vanilleeis',
        'Vanillekipferl',
        'Vanillepudding',
        'Vanillerostbraten',
        'Vanillezucker',
        'Vanillinzucker',
        'Vollkornbrot',
        'Vollkornmehl',
        'Vollmilchpulver',
        'Vollmilchschokolade',
        'Vollrohrzucker',
        'Walnuss',
        'Wasabi',
        'Wassermelone',
        'Wassersuppe',
        'Weichkäse',
        'Weihnachtsgebäck',
        'Weintraube',
        'Weißbrot',
        'Weißkohl',
        'Weißkraut',
        'Weißschimmelkäse',
        'Weißweinessig',
        'Weizen',
        'Weizengrieß',
        'Weizenmehl',
        'Wirsing',
        'Wurst',
        'Wurstbrühe',
        'Wurstsuppe',
        'Xanthan',
        'Xylit',
        'Xylitol',
        'Yams',
        'Yuzu',
        'Yoghurt',
        'Zander',
        'Zartbitterschokolade',
        'Zaziki',
        'Ziegenkäse',
        'Ziegenmilch',
        'Zimt',
        'Zimtstange',
        'Zitronat',
        'Zitrone',
        'Zitronensaft',
        'Zucchini',
        'Zucker',
        'Zuckerguss',
        'Zuckerrübensirup',
        'Zwetschge',
        'Zwiebel',
        'Zwiebelkuchen',
        'Zwiebelring',
        'Zwiebelsuppe',
        'Äpfel',
        'Öl',
        'Überraschungsei'
    ];


    public function __construct(private readonly UserPasswordHasherInterface $passwordHasher, private readonly UserRepository $userRepository)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addArgument('admin', InputArgument::OPTIONAL, 'creates an admin user');
    }

    /**
     * @throws Exception
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $isAdmin = $input->getArgument('admin');

        if ($isAdmin) {
            $io->note('Generating an admin!');
        }

        $user = new User();

        $user->setPhone($io->ask('Phone number*'));
        $user->setDisplayName($io->ask('Display name*'));
        $user->setFirstname($io->ask('Firstname'));
        $user->setLastname($io->ask('Lastname'));
        $user->setEmail($io->ask('email'));
        $user->setPassword($this->passwordHasher->hashPassword($user, $io->ask('password', $this->suggestPassword())));
        $user->setActive($io->confirm('set active'));
        $user->setScore(3);
        //$user->setNeedToChangePassword($io->confirm('need to change password after login', true));

        if ($isAdmin) {
            $user->setRoles(['ROLE_USER', 'ROLE_ADMIN']);
        } else {
            $user->setRoles(['ROLE_USER']);
        }

        try {
            $this->userRepository->save($user, true);
        } /** @noinspection PhpRedundantCatchClauseInspection */ catch (UniqueConstraintViolationException) {
            $io->error('Unique constraint violation: phonenumber or display name already registered');

            return Command::FAILURE;
        } catch (Throwable $t) {
            $io->error('Unexpected failure ' . $t->getMessage());

            return Command::FAILURE;
        }

        return Command::SUCCESS;
    }

    /**
     * @throws Exception
     */
    private function suggestPassword(): string
    {
        $passParts = [];
        $size = count(self::PASSWORD_PARTS);
        for ($i = 0; $i < 3; $i++) {
            $passParts[] = self::PASSWORD_PARTS[random_int(0, $size - 1)];
        }

        return implode('-', $passParts);
    }
}
