twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        appTitle: '%app.title%'
        locales: '%app.supported_locales%'
        version: '%app.version%'

when@test:
    twig:
        strict_variables: true
