name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DHOST:
        description: 'example.org'
        required: true
        type: string
      DUSER:
        description: ''
        required: true
        type: string
      DPASSWORD:
        description: ''
        required: true
        type: string

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate_key
        id: generate_number
        run: echo "random_number=$(($RANDOM))" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - run: sudo apt install lftp
      - run: sshpass -p ${{ inputs.DPASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DUSER }}@${{ secrets.DHOST }}:/.env.local.php .env.local.php
      - uses: php-actions/composer@v6
      - run: echo '<?php return "${{ steps.generate_number.outputs.random_number }}"; ' > ./public/deploy/ci.php
      - run: lftp -e "mirror -R . ." -u ${{ inputs.DUSER }},${{ inputs.DPASSWORD }} ${{ inputs.DHOST }}
      - run: curl https://deployment:${{ steps.generate_number.outputs.random_number }}@${{ secrets.HOST }}/deploy.php


