name: deployment
run-name: Deploy to ${{ vars.WEB_HOST }} by @${{ github.actor }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: sudo apt install lftp
      - name: generate deployment key
        id: generate_number
        run: echo "random_number=$(($RANDOM))" >> $GITHUB_OUTPUT
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare .env
        run: |
          echo APP_ENV=prod >> .env
          echo APP_DEBUG=false >> .env
          echo APP_SECRET=${{ secrets.APP }} >> .env
          echo DATABASE_URL="mysql://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:3306/${{ vars.DB_NAME }}?serverVersion=mariadb-10.8.3&charset=utf8mb4" >> .env
      - name: run composer
        uses: php-actions/composer@v6
      - name: dump-env
        uses: php-actions/composer@v6
        with:
          command: symfony:dump-env prod
      - run: cat .env.local.php
      - run: echo '<?php return "${{ steps.generate_number.outputs.random_number }}"; ' > ./public/ci.php
#      - run: |
#          echo '<html>die App wird gerade aktualisiert bitte haben sie etwas Geduld und versuchen sie es in 5 minuten noch einmal.<br>' > index.php
#          echo 'the App is updated right now please be patient and try again in 5 minutes</html>' >> index.php
      - name: prepare files to deploy
        run: |
          mkdir deploy
          mv bin deploy/
          mv config deploy/
          mv migrations deploy/
          mv public deploy/
          mv src deploy/
          mv templates deploy/
          mv translations deploy/
          sudo mv var deploy/
          sudo mv vendor deploy/
          mv .env.local.php deploy/
          mv composer.* deploy/
          mv symfony.lock deploy/
#          mv deploy/public/index.php index.php_bak
#      - name: clean target
#        run: echo not implemented yet
#      - name: activate maintenance info
#        run: echo not implemented yet
#      - name: copy files to target
#        run: cd deploy;lftp -e "mirror -R --parallel=20" -u ${{ vars.DEPLOYMENT_USER }},${{ secrets.DEPLOYMENT_PASSWORD }} ${{ vars.DEPLOYMENT_HOST }}
#      - name: deactivate maintenance info
#        run: echo not implemented yet
      - name: execute migrations
        run: curl https://deployment:${{ steps.generate_number.outputs.random_number }}@${{ vars.WEB_HOST }}/deploy.php


