name: Tests
run-name: running tests triggered by action '${{ github.event_name }}' on '${{ github.ref_name }}' by @${{ github.actor }}

on:
  push:
    branches:
      - '**'
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install --working-dir=tools/php-cs-fixer
      - run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src --dry-run --diff

  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - run: composer install --working-dir=tools/phpstan
      - run: XDEBUG_MODE=off tools/phpstan/vendor/bin/phpstan analyse -c phpstan.neon

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: services
        run: XDEBUG_MODE=off bin/console lint:container
      - name: config
        run: XDEBUG_MODE=off bin/console lint:yaml config/**/*.yaml
      - name: templates
        run: XDEBUG_MODE=off bin/console lint:twig templates
      - name: translations
        run: XDEBUG_MODE=off bin/console lint:xliff translations/*

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3
        with:
          version: 9.6.6
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"