name: Test
on:
  push:
    branches:
      - '**'
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install --working-dir=tools/php-cs-fixer
      - run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src --dry-run --diff

  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - run: composer install --working-dir=tools/phpstan
      - run: XDEBUG_MODE=off tools/phpstan/vendor/bin/phpstan analyse -c phpstan.neon

  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3
        with:
          version: 9.6.6
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"